import React from 'react'

const Initiative = () => {
  return (
    <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Excepturi, rem dolor ullam nihil quis alias amet repellendus. Harum nihil incidunt natus corrupti dignissimos odit molestiae fugit, delectus minima aut sint nesciunt esse inventore commodi fugiat necessitatibus consectetur non totam reprehenderit eveniet sapiente error a voluptates suscipit? Autem dolorum, omnis architecto incidunt molestiae magni eum aperiam vel at! Praesentium odit asperiores, recusandae dolores sapiente, accusamus, voluptates ut in corrupti rerum nulla commodi cum fugiat aut! Exercitationem nemo inventore dignissimos quidem quasi odit tenetur ullam illum ipsum praesentium, aspernatur atque, pariatur architecto repudiandae culpa veritatis quos odio impedit deleniti vel in! Reprehenderit totam consequuntur soluta in error non dolor quam voluptas, magni est maiores, saepe, asperiores minus. Earum dolores natus ipsa maxime, possimus deleniti sunt libero reiciendis repellendus iure suscipit, autem cumque laboriosam velit voluptas id accusamus sapiente cupiditate quidem fuga voluptates. Tenetur dignissimos inventore, dicta assumenda a dolorem repudiandae expedita alias laudantium quae voluptatem consequuntur, eaque dolore doloremque officia possimus atque harum optio omnis totam incidunt officiis commodi. Vitae eaque libero ipsa deInitiativebitis. Modi et eos velit fugit eum sapiente accusantium beatae animi? Tenetur porro dignissimos cumque quisquam voluptas asperiores odio numquam quam ad, expedita vitae natus animi qui nam repellendus totam molestias. Vitae quaerat cumque delectus voluptatibus, at inventore consequatur quae aliquam molestias, magnam beatae blanditiis obcaecati odit aliquid quos, quia dignissimos distinctio! Facere consequatur suscipit saepe, et quasi magni sit quae laborum dignissimos maxime officia. Deserunt sunt corrupti ad commodi nostrum praesentium. Ullam maxime vel optio in. Perferendis at ullam in ipsam eaque et, officiis unde ratione explicabo voluptatem, nostrum doloribus molestiae quasi iusto quos similique atque tempore tempora possimus necessitatibus eum. Illum, blanditiis iusto! Aperiam dignissimos molestiae perspiciatis, facere sunt adipisci magnam odit nobis assumenda quisquam nulla rem aut ea et voluptatem quod fuga maiores quasi deserunt, voluptatum veniam! Ab ratione dolores reprehenderit animi beatae harum et, doloribus voluptatem provident eius, nihil ipsam, officia debitis! Molestiae officiis, vitae sequi maiores adipisci ut praesentium ullam voluptates facilis! Repudiandae iste suscipit eveniet ex at, rerum expedita nam beatae natus voluptatibus?
    </div>
  )
}

export default Initiative